services:
  - type: web
    name: EVG
    env: production
    plan: free
    buildCommand: "composer install --optimize-autoloader --no-dev"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: null
